sudo: false
language: php

php:
- 7.4

before_script:
  - cd ./update
  - travis_retry composer install --no-interaction --prefer-dist --no-progress
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

branches:
  only:
    - master

script:
  - vendor/bin/phpunit

after_script:
  - ./cc-test-reporter after-build  -t clover --exit-code $TRAVIS_TEST_RESULT
